### ISSUE TITLE
Splendid work!

### ISSUE THREAD

**Issue by vaseline555** [infamoussoap/ConvexHull#1]
Dear authors,
I would like to appreciate your great work.

As stated in [this paper](http://proceedings.mlr.press/v125/van-erven20a/van-erven20a.pdf), online optimization on a probability simplex is certainly a significant but difficult-to-solve task, but it seems to be solved by this work!

From my curiosity, I wonder if this work is comparable to the [Soft-Bayes](https://arxiv.org/abs/1901.02230) by Orseau et al., as this work shares some similarity with yours, Cauchy-Simplex.
(Correct me if I understood wrong; I am quite a novice in this field)

Kudos again and also thank you for open-sourced code!

Best,
Adam

**Comment by infamoussoap** [comment]
Hi Adam,

Thanks for all the kind words. It's much appreciated. Also, thanks for referring me to these papers. They are super helpful with future work I wish to do with our algorithm.

But to your question, indeed, online optimization on a probability simplex has been solved many times over. Also, it seems correct that the Soft-Bayes algorithm is identical to the Cauchy-Simplex. In fact, the Soft-Bayes algorithm, and thus also ours, has already been found in 1997 by Helmbold (Equation 7 in "A Comparison of New and Old Algorithms for a Mixture Estimation Problem" - Helmbold, et al.).

However, the main focus of our paper is not on online optimization over a simplex, hence why it only takes 1/2 a page in it. Our paper focuses on solving optimization problems with a probability simplex constraint. This is a problem that the Soft-Bayes cannot solve as it requires the p_i to be positive. But in a typical optimization problem, the p_i can be negative. In this situation, the Soft-Bayes is not the same as the Cauchy-Simplex.

One thing that I've noticed when I read various papers on online optimization is that the algorithms are usually created out of thin air, with not much justification as to why they do what they do. Instead, we justify the Cauchy-Simplex by deriving it from simple calculus. Because of this, one can use a similar method to perform optimization with other constraints. Which is the direction of our future work (particularly with orthogonal matrix and doubly stochastic matrix constraints).

Let me know if you have any other questions!

Best,
James

**Comment by vaseline555** [comment]
Thank you for your kind reply. I found it very helpful.
Though it hasn't been a long time for me studying this area (i.e., (online) convex optimization), I can't agree with you more for the quote:
> ...with not much justification as to why they do what they do

I hope this work be widely known.

Have a good day!
Thank you.
